server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.243.24:3306/audioBooks?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 111111
  mvc:
    view:
      prefix: /static/
      suffix: .html
      view-names: html
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
      connection:
        characterEncoding: utf-8
    show-sql: true

log4j:
  debug: true