server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.243.24:3306/audioBooks?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 111111
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    show-sql: true