server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.106.243.24:3306/audioBooks2?useUnicode=true&characterEncoding=utf-8&useSSL=true
    url: jdbc:mysql://39.108.73.166:3306/icecream?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
#    password: 111111
    password: 123456
  mvc:
    view:
      prefix: /static/
      suffix: .html
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    show-sql: false